apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb
data:
  initdb.sql: |-
    CREATE USER 'api'@'%' IDENTIFIED BY 'api.user1234.' ;
    CREATE USER 'testing'@'%' IDENTIFIED BY 'test.user1234.' ;
