apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webserver-deploy
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserver-deploy
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: webserverconfig
status: {}
